### ISSUE TITLE
memcached enabled and 'Error: no memcache module found'

### ISSUE THREAD

**Issue by anders-larsson** [voxpupuli/puppetboard#1025]
**Describe the bug**

When memcached is enabled container fails with `Error: no memcache module found`. Can be fixed creating a new container based on this with `RUN pip install python-memcached`. However, since no one else has complained about this I'm not sure if this is just user error.

**Puppetboard version**

Tested in with 5.1.0 and 5.3.0. Happens with both versions.

**Environment and installation method**

docker compose:
```yaml
puppetboard:
  ...
  environment:
    - ENABLE_CLASS=True
    - SCHEDULER_ENABLED=True
    - CACHE_TYPE=MemcachedCache
    - CACHE_MEMCACHED_SERVERS=memcached:11211
```
