### ISSUE TITLE
Unable to establish SSL connection to PuppetDB

### ISSUE THREAD

**Issue by KpuCko** [voxpupuli/puppetboard#1236]
Hi there,
I would start with this that, plain HTTP connection is working as expected.
I tried to switch to SSL connection because it is recommended and via plain-text I don't have access to some endpoints (for instance I get access denied when I open Puppetboard landing page - overview, the rest are working)

Long story short, I have tried many different ways of getting this working, but here are two tests which confirms that the SSL certificates I use are correct and for some reasons I can't get it working inside the Puppetboard, check this:

```
root@sofx1013dckr309.home.lan:~/tests/puppet# docker run --rm -it --network crafty-minimal -v "$(pwd)/ssl_puppetboard:/etc/puppetlabs/puppet/ssl" ghcr.io/voxpupuli/puppetboard sh
/usr/src/app $ python3 -c "import requests; print(requests.get('https://puppetdb:8081/pdb/meta/v1/version', cert=('/etc/puppetlabs/puppet/ssl/puppetboard-cert
.pem', '/etc/puppetlabs/puppet/ssl/puppetboard-key.pem'), verify='/etc/puppetlabs/puppet/ssl/ca-cert.pem').text)"
{
  "version" : "8.8.1"
}
/usr/src/app $
root@sofx1013dckr309.home.lan:~/tests/puppet#
```

But when I try to run it via Docker compose:

```
root@sofx1013dckr309.home.lan:~/tests/puppet# docker compose up puppetboard
[+] Running 1/0
 ✔ Container puppet-puppetboard-1  Recreated                                                                                                             0.1s
Attaching to puppetboard-1
puppetboard-1  | ERROR:pypuppetdb.api.base:Could not reach PuppetDB on puppetdb:8081 over HTTPS.
puppetboard-1  | ERROR:puppetboard.utils:HTTPSConnectionPool(host='puppetdb', port=8081): Max retries exceeded with url: /pdb/meta/v1/version (Caused by SSLError(SSLError(524297, '[SSL] PEM lib (_ssl.c:3916)')))
puppetboard-1 exited with code 2
root@sofx1013dckr309.home.lan:~/tests/puppet#
```

Here is stanza of my Docker compose file:

```
  puppetboard:
    image: ghcr.io/voxpupuli/puppetboard
    hostname: puppetboard
    environment:
      PUPPETDB_HOST: puppetdb
      PUPPETDB_PORT: 8081
      PUPPETBOARD_PORT: 8080
      ENABLE_CATALOG: true
      PUPPETDB_SSL_VERIFY: /etc/puppetlabs/puppet/ssl/ca-cert.pem
      PUPPETDB_KEY: /etc/puppetlabs/puppet/ssl/puppetboard-key.pem
      PUPPETDB_CERT: /etc/puppetlabs/puppet/ssl/puppetboard-key.pem
      SECRET_KEY: "975785961fcbf03ae344f498d9957410507bf200ae1fde7110567c7c749a4ace"
      DEFAULT_ENVIRONMENT: "*"
    volumes:
      - ./ssl_puppetboard:/etc/puppetlabs/puppet/ssl
    ports:
      - 8282:8080
    restart: none
```
